-- migrations/001_initial.sql
-- Choose or Dare — initial D1 schema
-- Run with:
--   npx wrangler d1 execute choose-or-dare --local  --file=../migrations/001_initial.sql
--   npx wrangler d1 execute choose-or-dare --remote --file=../migrations/001_initial.sql

-- ── Users ──────────────────────────────────────────────────────────────────
-- One row per Firebase UID. Created/upserted on first login.
CREATE TABLE IF NOT EXISTS users (
  uid             TEXT    PRIMARY KEY,          -- Firebase UID
  display_name    TEXT    NOT NULL DEFAULT '',
  photo_url       TEXT    NOT NULL DEFAULT '',
  created_at      INTEGER NOT NULL DEFAULT (unixepoch()),
  total_sessions  INTEGER NOT NULL DEFAULT 0,
  total_dares     INTEGER NOT NULL DEFAULT 0,
  total_truths    INTEGER NOT NULL DEFAULT 0,
  bravery_score   REAL    NOT NULL DEFAULT 0.0  -- computed metric
);

-- ── Sessions ───────────────────────────────────────────────────────────────
-- One row per completed game session.
CREATE TABLE IF NOT EXISTS sessions (
  id            TEXT    PRIMARY KEY,            -- UUID generated by worker
  host_uid      TEXT    NOT NULL REFERENCES users(uid),
  started_at    INTEGER NOT NULL DEFAULT (unixepoch()),
  ended_at      INTEGER,                        -- NULL while in progress
  player_count  INTEGER NOT NULL DEFAULT 0,
  total_rounds  INTEGER NOT NULL DEFAULT 0,
  categories    TEXT    NOT NULL DEFAULT '[]'   -- JSON array of category keys
);

-- ── History ────────────────────────────────────────────────────────────────
-- One row per card played. Immutable after insert.
CREATE TABLE IF NOT EXISTS history (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id       TEXT    NOT NULL REFERENCES sessions(id),
  uid              TEXT    NOT NULL REFERENCES users(uid),
  player_name      TEXT    NOT NULL DEFAULT '',
  card_text        TEXT    NOT NULL DEFAULT '',
  card_type        TEXT    NOT NULL DEFAULT 'dare',  -- 'dare' | 'choose'
  category         TEXT    NOT NULL DEFAULT '',
  result           TEXT    NOT NULL DEFAULT 'PENDING', -- 'PENDING'|'DONE'|'SKIPPED'
  timestamp        INTEGER NOT NULL DEFAULT (unixepoch()),
  duration_seconds INTEGER NOT NULL DEFAULT 0
);

-- ── Custom Cards ───────────────────────────────────────────────────────────
-- User-created cards, scoped to the owning UID.
CREATE TABLE IF NOT EXISTS custom_cards (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  uid           TEXT    NOT NULL REFERENCES users(uid),
  text          TEXT    NOT NULL,
  type          TEXT    NOT NULL DEFAULT 'dare',  -- 'dare' | 'choose'
  category      TEXT    NOT NULL DEFAULT 'CUSTOM',
  difficulty    INTEGER NOT NULL DEFAULT 3,       -- 1–5
  is_adult_only INTEGER NOT NULL DEFAULT 0,       -- 0 | 1 (boolean)
  created_at    INTEGER NOT NULL DEFAULT (unixepoch())
);

-- ── Cards (built-in deck) ──────────────────────────────────────────────────
-- Seeded by migrations/002_seed_cards.sql.
CREATE TABLE IF NOT EXISTS cards (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  text          TEXT    NOT NULL,
  type          TEXT    NOT NULL DEFAULT 'dare',  -- 'dare' | 'choose'
  category      TEXT    NOT NULL,
  difficulty    INTEGER NOT NULL DEFAULT 3,       -- 1–5
  is_adult_only INTEGER NOT NULL DEFAULT 0,       -- 0 | 1
  times_used    INTEGER NOT NULL DEFAULT 0,
  is_custom     INTEGER NOT NULL DEFAULT 0        -- always 0 for built-in
);

-- ── Indexes ────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_history_uid
  ON history (uid);

CREATE INDEX IF NOT EXISTS idx_history_session
  ON history (session_id);

CREATE INDEX IF NOT EXISTS idx_history_timestamp
  ON history (timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_cards_category_adult
  ON cards (category, is_adult_only);

CREATE INDEX IF NOT EXISTS idx_custom_cards_uid
  ON custom_cards (uid);
