#!/usr/bin/env node
// scripts/generate-seed.js
// Generates migrations/002_seed_cards.sql with 320 real party-game cards.
// Run: node scripts/generate-seed.js
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, '../migrations/002_seed_cards.sql');

// UUID v4 expression for SQLite (no external deps needed in D1)
const UUID = `(lower(hex(randomblob(4)))||'-'||lower(hex(randomblob(2)))||'-4'||substr(lower(hex(randomblob(2))),2)||'-'||lower(hex(randomblob(2)))||'-'||lower(hex(randomblob(6))))`;

// card: [text, type, category, difficulty, is_adult_only]
const cards = [
// â”€â”€â”€ FRIENDLY TRUTHS (40) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
['What is the most embarrassing thing that has ever happened to you in public?','choose','FRIENDLY',1,0],
['What food combination do you eat in secret that others would find completely disgusting?','choose','FRIENDLY',1,0],
['What is the strangest dream you have ever had about someone you actually know?','choose','FRIENDLY',2,0],
['What is a habit you have that you would be embarrassed if anyone else found out about?','choose','FRIENDLY',2,0],
['What is the most childish thing you still do regularly as a fully grown adult?','choose','FRIENDLY',1,0],
['What is the weirdest thing you have searched for online late at night?','choose','FRIENDLY',2,0],
['What is the most embarrassing song you secretly love and listen to when alone?','choose','FRIENDLY',1,0],
['What did you do as a child that still makes you cringe when you think about it today?','choose','FRIENDLY',1,0],
['Have you ever walked into a glass door or wall in front of other people? Describe it.','choose','FRIENDLY',1,0],
['What is the most ridiculous thing you have ever genuinely cried about?','choose','FRIENDLY',1,0],
['What is the pettiest argument you have ever had with another person?','choose','FRIENDLY',2,0],
['What is the most useless talent you have that you are secretly quite proud of?','choose','FRIENDLY',1,0],
['What was the last thing you googled that you would never want anyone else to see?','choose','FRIENDLY',2,0],
['What is the most embarrassing photo of yourself that still exists somewhere?','choose','FRIENDLY',2,0],
['Have you ever pretended to be sick just to get out of something? What was it?','choose','FRIENDLY',2,0],
['What is the worst haircut or fashion choice you have ever made in your life?','choose','FRIENDLY',1,0],
['What is something you firmly believed as a child that turned out to be completely wrong?','choose','FRIENDLY',1,0],
['What is the dumbest way you have ever managed to injure yourself?','choose','FRIENDLY',1,0],
['What is the most embarrassing autocorrect fail you have ever had?','choose','FRIENDLY',1,0],
['What is the most embarrassing thing your parents have ever caught you doing?','choose','FRIENDLY',3,0],
['If your browser history was on screen right now, how panicked would you be from one to ten?','choose','FRIENDLY',2,0],
['What is the most awkward thing that has happened to you on public transport?','choose','FRIENDLY',1,0],
['What movie or show makes you cry every single time no matter how often you watch it?','choose','FRIENDLY',1,0],
['What is a completely irrational fear that you have never been able to shake?','choose','FRIENDLY',2,0],
['Have you ever laughed at a completely inappropriate moment? What happened?','choose','FRIENDLY',2,0],
['What is the most embarrassing thing you have done while trying to impress someone?','choose','FRIENDLY',2,0],
['What is your most embarrassing nickname and who in your life gave it to you?','choose','FRIENDLY',1,0],
['Have you ever accidentally called a teacher or boss by the wrong name in front of everyone?','choose','FRIENDLY',1,0],
['What is the most embarrassing thing you have done at a party or social gathering?','choose','FRIENDLY',2,0],
['Have you ever sent a voice note or video to the completely wrong person? What was in it?','choose','FRIENDLY',2,0],
['What is your most embarrassing fashion phase and how long did it unfortunately last?','choose','FRIENDLY',1,0],
['What childhood show or cartoon do you still secretly watch as a full adult?','choose','FRIENDLY',1,0],
['Have you ever tripped and fallen dramatically in front of a large crowd of people?','choose','FRIENDLY',1,0],
['What is the worst gift you have ever given someone and what was their actual reaction?','choose','FRIENDLY',1,0],
['What is the most embarrassing voicemail you have ever left for another person?','choose','FRIENDLY',2,0],
['Have you ever been caught talking loudly to yourself in public? What were you saying?','choose','FRIENDLY',2,0],
['What is a ridiculous belief you held as fact until embarrassingly recently in your life?','choose','FRIENDLY',2,0],
['What is the most embarrassing thing you have ever done while half asleep?','choose','FRIENDLY',2,0],
['What is one thing you do when no one is watching that you would never normally admit?','choose','FRIENDLY',2,0],
['What is the biggest social mistake you have ever made in front of a group of people?','choose','FRIENDLY',3,0],
// â”€â”€â”€ FRIENDLY DARES (40) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
['Do your best celebrity impression and keep going until someone correctly guesses who it is.','dare','FRIENDLY',2,0],
['Speak only in rhymes for the next two full minutes or accept a penalty from the group.','dare','FRIENDLY',2,0],
['Let the group give you an embarrassing nickname and use it for the rest of the game.','dare','FRIENDLY',1,0],
['Do your best runway walk across the room and back while the group scores you out of ten.','dare','FRIENDLY',2,0],
['Narrate everything you do for the next two minutes like a wildlife documentary presenter.','dare','FRIENDLY',2,0],
['Do your best impression of every single person in the group one by one without skipping anyone.','dare','FRIENDLY',2,0],
['Let the group pose you like a shop mannequin and hold that position for 30 full seconds.','dare','FRIENDLY',2,0],
['Invent and perform a 30-second commercial for the most ridiculous product the group thinks of.','dare','FRIENDLY',2,0],
['Do 10 jumping jacks while singing your favourite song as loudly as you possibly can.','dare','FRIENDLY',1,0],
['Talk in slow motion for two complete minutes no matter what anyone says to you.','dare','FRIENDLY',2,0],
['Pretend you are accepting an Oscar for the most embarrassing reason the group chooses.','dare','FRIENDLY',2,0],
['Act like a tour guide describing this room as if it is a world-famous museum exhibit.','dare','FRIENDLY',2,0],
['Let the group look through your gallery and show the most embarrassing photo they find to everyone.','dare','FRIENDLY',3,0],
['Do a dramatic reading of the last text you received as if it is a scene from Shakespeare.','dare','FRIENDLY',2,0],
['Be a completely still statue for one minute while the group tries everything to make you laugh.','dare','FRIENDLY',2,0],
['Do your best air guitar performance to a song chosen by the group for at least 30 seconds.','dare','FRIENDLY',1,0],
['Describe your entire day so far as if you are an excited sports commentator at a major final.','dare','FRIENDLY',2,0],
['Read out the last five things you searched for online in your most dramatic theatrical voice.','dare','FRIENDLY',2,0],
['Let the group choreograph a five-second dance and perform it five times in a row perfectly.','dare','FRIENDLY',1,0],
['Try to say the entire alphabet while doing a continuous squat without standing up at all.','dare','FRIENDLY',2,0],
['Do your best impression of someone receiving increasingly shocking bad news for 30 seconds.','dare','FRIENDLY',2,0],
['Speak with an accent chosen by the group for your next three full turns without breaking.','dare','FRIENDLY',2,0],
['Perform your best robot dance for exactly 20 seconds without ever breaking character.','dare','FRIENDLY',1,0],
['Act out a scene from a famous film using only animal sounds and absolutely no human words.','dare','FRIENDLY',2,0],
['Let the person on your left style your hair however they want and keep it for the rest of the game.','dare','FRIENDLY',2,0],
['Sing the entire alphabet backwards as fast as you possibly can without stopping.','dare','FRIENDLY',2,0],
['Do a movie trailer voiceover for 30 seconds promoting the most boring event imaginable.','dare','FRIENDLY',2,0],
['Let the group go through your recent emoji history and read out what you sent them with.','dare','FRIENDLY',2,0],
['Invent a completely fictional line dance right now and teach every person in the group the moves.','dare','FRIENDLY',2,0],
['Beatbox the chorus of a song chosen by the group for at least 30 uninterrupted seconds.','dare','FRIENDLY',2,0],
['Stand on a chair and deliver a passionate one-minute speech about why socks are underrated.','dare','FRIENDLY',2,0],
['Call a contact and convince them without lying that something incredible just happened nearby.','dare','FRIENDLY',3,0],
['Do an impression of how you imagine a cat experiences a Monday morning for 20 full seconds.','dare','FRIENDLY',1,0],
['Accept an award for the most average achievement in history and give a deeply tearful speech.','dare','FRIENDLY',2,0],
['Let the group give you a word and use it naturally in every sentence you say for two minutes.','dare','FRIENDLY',2,0],
['Perform your most convincing impression of a washing machine going through its full spin cycle.','dare','FRIENDLY',1,0],
['Try to juggle three random items from around the room and keep trying for 30 seconds.','dare','FRIENDLY',2,0],
['Do a dramatic ten-second entrance as if you are the most important person at a royal banquet.','dare','FRIENDLY',2,0],
['Let the group pick a forbidden word and then immediately try to make you say it for two minutes.','dare','FRIENDLY',2,0],
['Spend 30 seconds describing the person to your right as if introducing them to a talent show audience.','dare','FRIENDLY',1,0],
// â”€â”€â”€ PARTY TRUTHS (40) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
['What is the most embarrassing text you have ever sent to completely the wrong person?','choose','PARTY',3,0],
['Tell us about the wildest night out you have ever had in under one minute.','choose','PARTY',3,0],
['What is the biggest lie you have told that you genuinely got away with?','choose','PARTY',3,0],
['Have you ever cheated at a game or competition? Tell us exactly what happened.','choose','PARTY',3,0],
['What is the most rebellious thing you did as a teenager that your parents never discovered?','choose','PARTY',3,0],
['What is the worst decision you have ever made at a party or social event?','choose','PARTY',3,0],
['Have you ever pretended to genuinely like someone you found deeply annoying? Who was it?','choose','PARTY',3,0],
['What is the most embarrassing thing you have done when extremely tired or under pressure?','choose','PARTY',2,0],
['Who in this group would last longest on a desert island and who would give up first?','choose','PARTY',2,0],
['What is the most outrageous rumour you have ever started or helped spread?','choose','PARTY',4,0],
['What is the worst date you have ever been on? Give us the full honest story.','choose','PARTY',3,0],
['Have you ever taken something that was not yours? What happened?','choose','PARTY',3,0],
['What is the most embarrassing thing you have done in front of someone you had a crush on?','choose','PARTY',3,0],
['Have you ever completely ghosted someone without any explanation? Why did you do it?','choose','PARTY',3,0],
['What is the dumbest thing you have ever spent a significant amount of money on?','choose','PARTY',2,0],
['What is one opinion you hold that you know most people here would strongly disagree with?','choose','PARTY',3,0],
['Who in this group would you trust with your most important secret and who absolutely not?','choose','PARTY',3,0],
['Have you ever gotten into trouble with authority figures or the law? What happened?','choose','PARTY',4,0],
['What is the most embarrassing thing you have posted on social media and then deleted?','choose','PARTY',2,0],
['Have you ever told a lie that spiralled so far out of control you could not stop it?','choose','PARTY',3,0],
['What is the most petty revenge you have ever taken on someone who wronged you?','choose','PARTY',3,0],
['Have you ever dramatically overreacted to something completely minor in front of other people?','choose','PARTY',2,0],
['What did you do that you thought was genuinely cool at the time but now cringe about?','choose','PARTY',2,0],
['What is the most desperate thing you have ever done to get another person to notice you?','choose','PARTY',3,0],
['Have you ever fallen completely asleep somewhere wildly inappropriate? Where was it?','choose','PARTY',3,0],
['What is the most embarrassing fake reason you have ever given for calling in sick?','choose','PARTY',2,0],
['Have you ever been removed or asked to leave somewhere? Tell us the full story.','choose','PARTY',4,0],
['What is the worst thing you have done to get out of a social obligation you dreaded?','choose','PARTY',3,0],
['Have you ever pretended to have skills or talents you did not have to impress someone?','choose','PARTY',2,0],
['What is the most ridiculous thing you have been genuinely afraid of as a full adult?','choose','PARTY',2,0],
['Have you ever broken something valuable belonging to someone else and never told them?','choose','PARTY',3,0],
['Have you ever walked in on something you truly wish you could completely unsee?','choose','PARTY',3,0],
['What is the most embarrassing thing someone has witnessed you doing when you thought you were alone?','choose','PARTY',3,0],
['Have you ever deliberately avoided someone in public and pretended not to see them?','choose','PARTY',2,0],
['What is one thing you have done that you would be ashamed for your parents to discover?','choose','PARTY',4,0],
['What is the most impulsive decision you have ever made and what was the actual aftermath?','choose','PARTY',3,0],
['What is the most ridiculous argument you have ever had with a complete stranger?','choose','PARTY',3,0],
['Have you ever pretended to be a different kind of person to get something you wanted?','choose','PARTY',3,0],
['What is the most embarrassing thing you have done that at least three people witnessed?','choose','PARTY',3,0],
['What is the boldest thing you have ever done purely on impulse with zero planning?','choose','PARTY',4,0],
// â”€â”€â”€ PARTY DARES (40) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
['Call a random contact and sing them Happy Birthday all the way through right now.','dare','PARTY',4,0],
['Let the group compose and send one text from your phone to a contact they choose right now.','dare','PARTY',4,0],
['Do 20 push-ups while the group counts aloud. Miss any and restart from zero.','dare','PARTY',3,0],
['Let the group change your profile photo on a social media platform of their choice for one hour.','dare','PARTY',4,0],
['Post a status right now that the group writes for you word for word.','dare','PARTY',4,0],
['Call a family member and tell them you have exciting news, then describe the room dramatically.','dare','PARTY',3,0],
['Go outside and shout a phrase the group chooses at the absolute maximum volume you can manage.','dare','PARTY',4,0],
['Let the group scroll your last 50 photos and caption any three they find out loud to everyone.','dare','PARTY',3,0],
['Perform a full stand-up comedy routine for two minutes on a topic the group picks for you.','dare','PARTY',3,0],
['Show the group the single most embarrassing photo in your camera roll without editing anything.','dare','PARTY',3,0],
['Call a friend not in the group and convince them you are currently at a completely different location.','dare','PARTY',4,0],
['Do a dramatic interpretive dance to a song chosen entirely by the group right now.','dare','PARTY',3,0],
['Read out your full search history from the past 24 hours without skipping a single entry.','dare','PARTY',3,0],
['Go to the nearest window and wave enthusiastically at the next person you see outside.','dare','PARTY',2,0],
['Recreate your most embarrassing memory as a fully committed silent mime for the group.','dare','PARTY',3,0],
['Sing a complete one-minute opera version of your entire day so far with maximum drama.','dare','PARTY',3,0],
['Take the most unflattering selfie possible and set it as your phone lock screen for one hour.','dare','PARTY',3,0],
['Do an enthusiastic unboxing video reaction to a completely ordinary random item from the room.','dare','PARTY',2,0],
['Let the group film a 15-second video of you doing whatever they decide without refusal.','dare','PARTY',4,0],
['Attempt to start a slow clap in this group right now and get every single person to join.','dare','PARTY',2,0],
['Let the group compose a dating profile for you out loud and respond to each point with only yes or no.','dare','PARTY',3,0],
['Pretend you are being interviewed live on a chat show and answer any three questions the group asks.','dare','PARTY',3,0],
['Give a passionate two-minute TED Talk style speech on the most boring topic the group can think of.','dare','PARTY',3,0],
['Let the group act as your personal stylist and rearrange your outfit using whatever is available.','dare','PARTY',3,0],
['Call a contact and convince them using only questions to agree to meet you in 20 minutes.','dare','PARTY',4,0],
['Let the group set a mystery alarm on your phone to go off at a time they secretly decide for tomorrow.','dare','PARTY',3,0],
['Do a complete live impression of each person in the group for at least ten seconds each.','dare','PARTY',3,0],
['Let the group set your social media bio to whatever they want right now for 24 full hours.','dare','PARTY',4,0],
['Let the person on your left give you a full makeover using whatever items are available right now.','dare','PARTY',3,0],
['Perform a 60-second motivational speech convincing the group that you deserve a standing ovation.','dare','PARTY',2,0],
['Let the group pick a challenge for you to complete in the next 24 hours and report back with proof.','dare','PARTY',4,0],
['Do your best impression of how each person would react to winning a million dollars.','dare','PARTY',3,0],
['Let the group narrate a nature documentary about you for 60 seconds while you act out what they say.','dare','PARTY',3,0],
['Have a one-minute serious conversation about the weather using only song lyrics.','dare','PARTY',3,0],
['Let the group pick a memory you mentioned tonight and retell it in a completely different accent.','dare','PARTY',2,0],
['Stand on a chair and deliver a 60-second farewell speech as if you are leaving this group forever.','dare','PARTY',3,0],
['Let the group compose a formal complaint letter from you to a celebrity they choose and read it aloud.','dare','PARTY',3,0],
['Do a news anchor impression reporting on the most boring thing that happened in this room today.','dare','PARTY',2,0],
['Let the group assign you a made-up job title and explain your role convincingly for 60 seconds.','dare','PARTY',2,0],
['Recreate the most dramatic film scene you can think of using only people and objects in this room.','dare','PARTY',3,0],
// â”€â”€â”€ COUPLES TRUTHS (40) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
['What was your completely honest first impression of your partner the very first day you met?','choose','COUPLES',2,1],
['What is one thing your partner does that you find secretly adorable but have never told them?','choose','COUPLES',2,1],
['What is the most embarrassing moment you have had in front of your partner?','choose','COUPLES',2,1],
['What was the first physical thing you noticed about your partner that attracted you to them?','choose','COUPLES',2,1],
['What is one small habit of your partner that you find mildly annoying but have never mentioned?','choose','COUPLES',3,1],
['Describe your partner in exactly three words then ask if they agree with your choices.','choose','COUPLES',2,1],
['What is something your partner is genuinely better at than you that you would never admit aloud?','choose','COUPLES',3,1],
['What is the most ridiculous argument you and your partner have ever had together?','choose','COUPLES',2,1],
['What is one thing you changed about yourself after getting into a relationship with your partner?','choose','COUPLES',3,1],
['What is one thing about your partner that you still find attractive after all this time?','choose','COUPLES',2,1],
['Have you ever been jealous of your partner without telling them? What caused it?','choose','COUPLES',3,1],
["What is your partner's single most embarrassing habit that they think you have not noticed?","choose","COUPLES",3,1],
['What was the exact moment you knew you were genuinely falling in love with your partner?','choose','COUPLES',2,1],
['What is something you said to your partner early on that you now deeply regret?','choose','COUPLES',3,1],
['What is one question you have always wanted to ask your partner but never found the courage to?','choose','COUPLES',4,1],
['What is something about your relationship that outsiders might find strange but you both love?','choose','COUPLES',2,1],
['Have you ever kept a significant secret from your partner that they still do not know?','choose','COUPLES',4,1],
['What is the most romantic or thoughtful thing your partner has ever done for you?','choose','COUPLES',2,1],
['What is the single thing you love most about being in a relationship with this person?','choose','COUPLES',2,1],
['What are three things you deeply appreciate about your partner that you never say enough?','choose','COUPLES',2,1],
['Describe the first time you introduced your partner to your family or close friends.','choose','COUPLES',2,1],
['What is one personal dream you have not yet shared openly with your partner?','choose','COUPLES',4,1],
['What do you think is the single biggest difference between you and your partner?','choose','COUPLES',2,1],
['What is something about your partner that someone else pointed out that you had never noticed?','choose','COUPLES',2,1],
['Have you ever felt genuinely embarrassed by something your partner said or did in public?','choose','COUPLES',3,1],
['Who said I love you first and what was the exact reaction of the other person?','choose','COUPLES',2,1],
['What is your single favourite memory of the two of you together from the past year?','choose','COUPLES',2,1],
['What is something your partner does that instantly makes you feel better when you are stressed?','choose','COUPLES',2,1],
['What would you most want your partner to genuinely work on improving about themselves?','choose','COUPLES',4,1],
['Have you ever seriously imagined what your life would look like without this partner?','choose','COUPLES',4,1],
['What is the funniest or most absurd thing your partner has ever done completely by accident?','choose','COUPLES',2,1],
['What is one thing from before this relationship that you sometimes miss but would not trade away?','choose','COUPLES',3,1],
['What is something you want to do with your partner that you have never found the courage to suggest?','choose','COUPLES',4,1],
['What was the worst date you and your partner ever went on together and what went wrong?','choose','COUPLES',2,1],
['Have you ever told your partner a white lie to avoid a disagreement? What was it about?','choose','COUPLES',3,1],
['What is one thing you wish had been different about how your relationship started?','choose','COUPLES',3,1],
['What has been the hardest moment in your relationship and how did you both get through it?','choose','COUPLES',4,1],
['What do you think your partner secretly finds most attractive about you as a person?','choose','COUPLES',2,1],
['What is one thing you do for your partner that you hope they truly notice and appreciate?','choose','COUPLES',2,1],
['What is the most vulnerable thing you have shared with your partner that took real courage?','choose','COUPLES',4,1],
// â”€â”€â”€ COUPLES DARES (40) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
['Give your partner a genuine 60-second shoulder massage right now without stopping.','dare','COUPLES',2,1],
['Whisper the most romantic thing you can genuinely think of into your partner''s ear right now.','dare','COUPLES',2,1],
["Look into your partner's eyes without laughing or looking away for a full 30 seconds.","dare","COUPLES",3,1],
['Re-enact your very first date together in 60 seconds with your partner right now.','dare','COUPLES',3,1],
['Tell your partner three completely specific things you love about them in under 20 seconds.','dare','COUPLES',2,1],
["Hold your partner's hand and recreate word for word the way you first introduced yourselves.","dare","COUPLES",2,1],
['Let your partner adjust one thing about your appearance that they have always wanted to change.','dare','COUPLES',2,1],
['Write your partner a short genuine poem about why you chose them and read it aloud to everyone.','dare','COUPLES',3,1],
['Do a slow dance with your partner for 30 seconds right now even if there is no music playing.','dare','COUPLES',3,1],
['Receive a compliment from your partner without deflecting, minimising, or making any joke.','dare','COUPLES',2,1],
['Tell your partner one specific thing they do that you find completely and genuinely irresistible.','dare','COUPLES',3,1],
['Give your partner a forehead kiss and tell them one reason you are genuinely proud of them.','dare','COUPLES',2,1],
['Let your partner list your top three most annoying habits aloud and respond only with thank you.','dare','COUPLES',4,1],
['Show your partner the last three things you searched for on your phone right now without filtering.','dare','COUPLES',3,1],
['Recreate the exact moment you first told each other you were falling in love as accurately as you can.','dare','COUPLES',3,1],
['Hold your partner''s face gently in both hands and describe what you see aloud for 20 seconds.','dare','COUPLES',2,1],
['Write a fake celebrity gossip headline about your relationship and read it dramatically to everyone.','dare','COUPLES',2,1],
['Tell your partner about the moment you realised you genuinely wanted to be with only them.','dare','COUPLES',3,1],
['List five specific things about your partner that you find attractive right now out loud.','dare','COUPLES',3,1],
['Apologise genuinely to your partner for one thing you have never properly said sorry for.','dare','COUPLES',4,1],
['Tell everyone one thing your partner does that you are secretly extremely proud of.','dare','COUPLES',2,1],
['Spend 60 seconds telling your partner everything specific you would miss about them if separated.','dare','COUPLES',3,1],
['Let your partner describe your relationship using only three emoji and guess what each one means.','dare','COUPLES',2,1],
['Challenge your partner to finish these sentences: I love you most when... I feel luckiest when...','dare','COUPLES',3,1],
['Tell your partner about a moment they helped you through something hard without realising it.','dare','COUPLES',3,1],
['Swap phones with your partner for exactly two minutes with absolutely no restrictions.','dare','COUPLES',4,1],
['List the top five songs that genuinely remind you of your relationship in order.','dare','COUPLES',2,1],
['Tell your partner the exact first thought you had the very first time you saw them.','dare','COUPLES',3,1],
['Re-enact your most embarrassing shared moment together for the group right now.','dare','COUPLES',3,1],
['Let the group ask your partner one honest question about you that they must answer truthfully.','dare','COUPLES',4,1],
['Write the opening sentence of the story of how you met and read it in your best voice.','dare','COUPLES',2,1],
['Tell your partner three ways they have made you a better person since you have been together.','dare','COUPLES',2,1],
['Describe your partner to the group using only names of songs and no other descriptive words.','dare','COUPLES',2,1],
['Take the most romantic photo together you can manage and make it both your lock screens now.','dare','COUPLES',3,1],
["Let your partner ask you one question they have wanted to ask for a long time and answer honestly.","dare","COUPLES",4,1],
['Make something together right now using only three ingredients or items currently available.','dare','COUPLES',3,1],
['Give your partner a handwritten note with one thing you want to do together in the next 30 days.','dare','COUPLES',2,1],
['Tell the group how you knew your partner was different from anyone you had met before.','dare','COUPLES',2,1],
['Let your partner rearrange your hair or adjust your look exactly however they have always wanted.','dare','COUPLES',2,1],
['Take turns listing one thing the other person does that makes daily life better until someone runs out.','dare','COUPLES',2,1],
// â”€â”€â”€ DIRTY TRUTHS (40) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
['What is the most daring thing you have ever done that you have never told another person?','choose','DIRTY',4,1],
['What is the wildest or most unexpected place you have ever been physically intimate?','choose','DIRTY',5,1],
['Have you ever had a serious crush on someone who was completely off-limits? Who were they?','choose','DIRTY',4,1],
['What is the most embarrassing thing that has ever happened to you in a romantic situation?','choose','DIRTY',4,1],
['Have you ever accidentally sent a risky photo or message to completely the wrong person?','choose','DIRTY',5,1],
['What is the most adventurous thing you have done or considered doing with a romantic partner?','choose','DIRTY',5,1],
['What is the most unexpected thing that has ever made you find someone surprisingly attractive?','choose','DIRTY',4,1],
['Have you ever been caught in an extremely compromising situation by someone you knew?','choose','DIRTY',5,1],
['What is the boldest pickup line you have ever actually used on another person?','choose','DIRTY',4,1],
['What is the most awkward or mortifying way a romantic encounter has ever ended for you?','choose','DIRTY',4,1],
['Have you ever pretended to be attracted to someone you were not at all? What was your reason?','choose','DIRTY',4,1],
['What is the most embarrassing romantic thought you have had about someone you probably should not?','choose','DIRTY',4,1],
["Have you ever used someone's clear attraction to you to get something you wanted from them?","choose","DIRTY",5,1],
['What is the most daring thing a romantic partner dared you to do and did you go through with it?','choose','DIRTY',5,1],
['Have you ever been romantically involved with two people at the same time without either knowing?','choose','DIRTY',5,1],
['What is the most direct or forward thing you have ever said to someone you had just met?','choose','DIRTY',4,1],
['What is one thing you have done inside a relationship that you have never confessed to any partner?','choose','DIRTY',5,1],
['What is the most unexpectedly passionate moment you have ever experienced with another person?','choose','DIRTY',4,1],
['Have you ever had a dream about someone in this group that you woke up feeling strange about?','choose','DIRTY',5,1],
['What is the most creative excuse you invented purely to spend time alone with someone you wanted?','choose','DIRTY',4,1],
['Have you ever flirted seriously with someone while already in a committed relationship?','choose','DIRTY',5,1],
['What is the most surprising quality you have discovered you are genuinely attracted to in a person?','choose','DIRTY',4,1],
['What is the boldest move you have ever made on someone you had only just met?','choose','DIRTY',4,1],
['Have you ever stayed with someone purely because of physical chemistry despite knowing it was wrong?','choose','DIRTY',5,1],
['What is the most reckless romantic decision you have ever made purely on impulse?','choose','DIRTY',5,1],
['Have you ever developed completely unexpected feelings for someone entirely off-limits to you?','choose','DIRTY',5,1],
['What is the most embarrassing thing someone has accidentally discovered about your romantic history?','choose','DIRTY',4,1],
["Have you ever been told you were someone's best experience and how did you react to hearing it?","choose","DIRTY",5,1],
['What is one thing you did in a relationship that you would be mortified if it ever became public?','choose','DIRTY',5,1],
['Have you ever completely lost your composure over someone who barely knew you existed?','choose','DIRTY',4,1],
['What is the most unexpected setting where you have ever felt an immediate powerful attraction?','choose','DIRTY',4,1],
['Have you ever done something completely out of character purely because of attraction to someone?','choose','DIRTY',4,1],
['What is the most scandalous secret someone confided in you that you have kept to this day?','choose','DIRTY',5,1],
['Have you ever been so attracted to someone that you acted completely unlike your normal self?','choose','DIRTY',4,1],
['What is the most daring look you have ever worn or seriously considered wearing for someone?','choose','DIRTY',4,1],
['Have you ever ended something genuinely good because someone more exciting appeared?','choose','DIRTY',5,1],
['What is the most surprising place you have ever met someone you were immediately attracted to?','choose','DIRTY',4,1],
['Have you ever persistently pursued someone despite being clearly told you had no chance?','choose','DIRTY',4,1],
['What is the most vulnerable moment you have shared with someone you were romantically involved with?','choose','DIRTY',5,1],
['What is one thing about your romantic past that you have never said out loud to anyone?','choose','DIRTY',5,1],
// â”€â”€â”€ DIRTY DARES (40) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
['Give the most convincingly seductive wink you can to the person sitting directly across from you.','dare','DIRTY',4,1],
['Do your slowest and most dramatic hair flip while maintaining eye contact with one person of your choice.','dare','DIRTY',4,1],
['Let the group vote on who has the most attractive smile and tell that person directly why.','dare','DIRTY',4,1],
['Whisper one genuine thing you find attractive about the person sitting directly to your left.','dare','DIRTY',4,1],
['Do your most convincing impression of someone completely and helplessly falling in love for 30 seconds.','dare','DIRTY',4,1],
['Tell the group the most romantic compliment you have ever received and who gave it to you.','dare','DIRTY',4,1],
['Read a random page from any book in the room in the most seductive voice you can manage.','dare','DIRTY',5,1],
['Describe the most physically attractive person in this room using only food metaphors for 30 seconds.','dare','DIRTY',4,1],
['Give a 30-second speech on why confidence is the single most attractive human quality.','dare','DIRTY',4,1],
['Tell the person on your right one very specific thing you genuinely find attractive about them.','dare','DIRTY',5,1],
['Do your most dramatic entrance into the room as if arriving at the most glamorous event of your life.','dare','DIRTY',4,1],
['Let the group pick a song and lip-sync the most compelling and seductive version you can manage.','dare','DIRTY',4,1],
['Spend 30 seconds explaining why you believe attraction is the most powerful force in human experience.','dare','DIRTY',4,1],
['Convince the person next to you using only genuine compliments to give you their seat right now.','dare','DIRTY',4,1],
['Perform a 60-second unrehearsed stand-up comedy routine about the reality of modern dating.','dare','DIRTY',4,1],
['Let the group write and deliver out loud a toast about your romantic history based on what they know.','dare','DIRTY',5,1],
['Describe your ideal romantic evening in complete precise detail to the group without hesitating.','dare','DIRTY',4,1],
['Give the person who has made you smile most tonight a completely genuine specific compliment.','dare','DIRTY',4,1],
['Let the group improvise a romance novel title and you speak the opening paragraph in 60 seconds.','dare','DIRTY',5,1],
['Tell the group honestly what the most attractive and confident version of yourself looks and acts like.','dare','DIRTY',5,1],
['Do a dramatic reading of a text the group composes together as if it is the most important ever written.','dare','DIRTY',4,1],
['Let the group cast who among them would play each role in a film about the story of your romantic life.','dare','DIRTY',4,1],
['Stand up and demonstrate what your ideal first impression looks like in a ten-second performance.','dare','DIRTY',4,1],
['Tell the group about a moment when you felt the most physically and emotionally confident in your life.','dare','DIRTY',5,1],
['Perform a 20-second roleplay scene where you are a charismatic spy using attraction as your main tool.','dare','DIRTY',5,1],
['Tell the group the three personal qualities you genuinely believe make you most attractive as a partner.','dare','DIRTY',4,1],
['Let the group decide your most appealing quality and use only that to convince them you deserve the last drink.','dare','DIRTY',5,1],
['Give a 45-second TED Talk style lecture on the science of why physical attraction happens.','dare','DIRTY',4,1],
['Let the group nominate the most charismatic person here to teach you their signature confident move.','dare','DIRTY',4,1],
['Tell the group about a time you felt completely irresistible and describe exactly what you were doing.','dare','DIRTY',5,1],
['Do a dramatic slow-motion 15-second solo walk across the room as if the group is a fashion show audience.','dare','DIRTY',4,1],
['Tell the group honestly what you consider your single most attractive physical feature and why.','dare','DIRTY',4,1],
['Let the group compose and read aloud a dating advertisement for you and respond to each line with one word.','dare','DIRTY',5,1],
['Describe in detail to the group what your ideal partner would be like without naming anyone in the room.','dare','DIRTY',4,1],
['Perform a 30-second scene where you charm your way into an exclusive VIP event using only words.','dare','DIRTY',5,1],
['Tell the group the three things you need to feel completely irresistible on a night out.','dare','DIRTY',4,1],
['Let the group pick one person and give them the most sincere compliment you can manage in 30 seconds.','dare','DIRTY',4,1],
['Recreate the most confident walk you have ever done in your life across the room right now.','dare','DIRTY',4,1],
['Tell the group one genuinely bold thing you have always wanted to say to someone but never dared to.','dare','DIRTY',5,1],
['Let the group describe your ideal partner trait by trait and react to each one with complete honesty.','dare','DIRTY',5,1],
];

const UUID = `(lower(hex(randomblob(4)))||'-'||lower(hex(randomblob(2)))||'-4'||substr(lower(hex(randomblob(2))),2)||'-'||lower(hex(randomblob(2)))||'-'||lower(hex(randomblob(6))))`;

const lines = [
  '-- migrations/002_seed_cards.sql',
  '-- 320 party game seed cards: 40 truths + 40 dares per category',
  '-- FRIENDLY (adult=0, diff 1-3), PARTY (adult=0, diff 2-4)',
  '-- COUPLES (adult=1, diff 2-4), DIRTY (adult=1, diff 4-5)',
  '',
];

for (const [text, type, cat, diff, adult] of cards) {
  const safe = text.replace(/'/g, "''");
  lines.push(
    `INSERT INTO cards(id,text,type,category,difficulty,is_adult_only) VALUES (${UUID},'${safe}','${type}','${cat}',${diff},${adult});`
  );
}

lines.push('');
writeFileSync(OUT, lines.join('\n'), 'utf8');
console.log(`Written ${cards.length} cards to ${OUT}`);


